### ISSUE TITLE
hello, on Rails 3....doesn't seem to work>

### ISSUE THREAD

**Issue by angelacode** [sjlombardo/acts_as_network#2]
Hi, wanted to know whether I am doing something wrong or how to debug, but I tried it on Rails 3, I have an Invite.rb model and an invitations_controller with a create action that is Invite.new(:params[:invite]) but the friends and invtations methods still show up as [].

**Comment by sjlombardo** [comment]
try the rails3 repo here https://github.com/erikh/acts_as_network/tree/rails3
